### ISSUE TITLE
Geo model inclusion on Android

### ISSUE THREAD

**Issue by jtklein** [inaturalist/vision-camera-plugin-inatvision#43]
Prerequisites

- [X] [Train a mobile geomodel for version 2.13](https://github.com/inaturalist/iNaturalistMLWork/issues/145)

Native side

- [x] Integrate the geomodel into the frame processor
- [x] Enable a module function to call the geomodel for a given location object, similar to getPredictionsForImage.

**Comment by alexshepard** [comment]
blocker is https://github.com/inaturalist/iNaturalistMLWork/issues/145

in the meantime, there are 2.4 tflite geo models available to test with:
/disk/mnt/nfs/ml_models/models/transfer_2_4_20230521/INatVision_2_4_fact256_unscaled_8bit.tflite
/disk/mnt/nfs/ml_models/models/transfer_2_4_20230521/tf_geoprior_2_4_r6_elevation_8bit.tflite
